# Generated by Django 4.1 on 2023-03-21 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_car_manufacturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'default_related_name': 'cars'},
        ),
        migrations.AlterField(
            model_name='car',
            name='drivers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.manufacturer'),
        ),
    ]
