# Generated by Django 4.1 on 2023-01-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_manufacturer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'car', 'verbose_name_plural': 'cars'},
        ),
    ]
