# Generated by Django 4.1 on 2023-03-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_car_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={},
        ),
    ]
