# Generated by Django 4.1 on 2024-03-18 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_alter_manufacturer_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ("first_name",)},
        ),
    ]
