# Generated by Django 4.1 on 2023-01-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_manufacturer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name']},
        ),
    ]
