# Generated by Django 4.1 on 2023-07-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_car_options_alter_driver_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={},
        ),
    ]
