# Generated by Django 4.1 on 2022-10-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_car_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['first_name'], 'verbose_name': 'driver', 'verbose_name_plural': 'drivers'},
        ),
    ]
