# Generated by Django 4.1 on 2023-05-12 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0003_alter_car_options_alter_driver_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ["manufacturer"]},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={
                "ordering": ["username"],
                "verbose_name": "driver",
                "verbose_name_plural": "drivers",
            },
        ),
    ]
