# Generated by Django 4.1 on 2023-03-24 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0004_alter_manufacturer_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manufacturer",
            options={},
        ),
    ]
